name: ParkourLeaderboard
version: ${project.version}
main: henry232323.parkourleaderboard.ParkourLeaderboard
authors: [henry232323]
softdepend: [HolographicDisplays]
description: A plugin for tracking leaderboards on your parkour

permissions:
  parkour.*:
    description: All permissions for parkour
    children:
      parkour.leaderboard: true
      parkour.reload: true
  parkour.leaderboard:
    description: Gives access to viewing the leaderboard
    default: true
  parkour.reload:
      description: Gives access to reloading the plugin
      default: op

commands:
   parkour:
     description: View the leaderboard for a parkour
     aliases: []
     permission: parkour.leaderboard
     usage: "§cSyntax error! Usage: /parkour <name>"
   preload:
     description: Reload the parkour plugin
     permission: parkour.reload
     usage: "§cSyntax error! Usage: /preload"
